# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration parameters
boxRam = 2048                      # Ram in MB
boxCpus = 2                        # Number of CPU core

ipythonPort = 8001                 # Ipython port to forward (also set in IPython notebook config)

Vagrant.configure(2) do |config|
  config.vm.define "sparkvm" do |master|
    master.vm.box = "ubuntu/trusty32"
    master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort   # IPython port (set in notebook config)
    master.vm.network :forwarded_port, host: 8000, guest: 8080                 # Spark UI (Driver)
    master.vm.hostname = "sparkvm"

    master.vm.provider :virtualbox do |v|
      v.name = master.vm.hostname.to_s
      v.customize ["modifyvm", :id, "--memory", "#{boxRam}"]
      v.customize ["modifyvm", :id, "--cpus", "#{boxCpus}"]
    end
    #master.vm.provision :shell, :path => "provision_spark_node.sh"
    if File.exist?(File.expand_path("../modules", __FILE__))
        puppet_root = File.expand_path("../", __FILE__)
    elsif File.exist?(File.expand_path("../../modules", __FILE__))
        puppet_root = File.expand_path("../../", __FILE__)
    elsif File.exist?(File.expand_path("../../../modules", __FILE__))
        puppet_root = File.expand_path("../../../", __FILE__)
    else
        puppet_root = nil
    end
    unless puppet_root.nil?
        config.vm.provision "puppet" do |puppet|
          puppet.manifests_path = "#{puppet_root}/manifests"
          puppet.module_path    = "#{puppet_root}/modules"
          puppet.manifest_file  = "site.pp"
        end
      end
  end
end
